/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.monke;

import com.github.monke.nodes.BSTNode
import com.github.monke.nodes.BinaryTreeNode
import com.github.monke.trees.BSTree
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        val classUnderTest =    Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

}
